export const FETCH_RECENTTEMP = 'FETCH_RECENTTEMP';
export const VERIFY_USER = 'VERIFY_USER';
export const FETCH_SENSOR_IDS = 'FETCH_SENSOR_IDS';
export const FETCH_TEMP_BY_SENSOR_IDS = 'FETCH_TEMP_BY_SENSOR_IDS';
export const FETCH_ALL_TEMP_BY_SENSOR_IDS = 'FETCH_ALL_TEMP_BY_SENSOR_IDS';
export const GET_CHART_DATA = 'GET_CHART_DATA';
